### ISSUE TITLE
Method A | failure handling

### ISSUE THREAD

**Issue by gintama1227** [JuPedSim/jpsreport#149] opened 2019-08-17 09:54 UTC
*JuPedSim - JPSreport**

- Current date   :2019/8/17
- Version        :0.8.4
- Compiler       :Visual Studio
- Commit hash    :
- Commit date    :
- Branch         : 
- Python         : 3.7

**Describe the bug**
No output of Method I. I try "jpsreport/demos/obstacle". But there is no output.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/34682823/63209715-1b6c4600-c117-11e9-8d10-7aa79115005d.png)
![image](https://user-images.githubusercontent.com/34682823/63209716-245d1780-c117-11e9-89fc-772e6800cf53.png)

**Additional context**
<method_I enabled="true"> 
        <measurement_area id="1" start_frame="None" stop_frame="None" /> 
        <cut_by_circle enabled="true" radius="1.0" edges="10"/>
		<one_dimensional enabled="false"/>
    </method_I> 

[log.txt](https://github.com/JuPedSim/jpsreport/files/3511877/log.txt)

**Comment by gjaeger** [comment] 2019-08-17 10:35
Can you please upload your modified ini-file?

The module `Polygon` is missing to execute the `_Plot_N_t.py`-file. Please check the [required tools](http://www.jupedsim.org/jpsreport/2016-11-03-requirements.html#required-tools).

**Comment by gintama1227** [comment] 2019-08-17 10:36
[ini_corridor.zip](https://github.com/JuPedSim/jpsreport/files/3511907/ini_corridor.zip)

**Comment by gjaeger** [comment] 2019-08-17 11:10
Your problem isn't a bug. If the module `Polygon` is missing, method A cannot be completed.

We can adapt JPSreport so that the absence of the module is correctly intercepted.

**Comment by gintama1227** [comment] 2019-08-17 11:14
Thank you, I installed Polygon3. But, I still cannot  use **Method I**.

**Comment by gintama1227** [comment] 2019-08-17 11:16
![image](https://user-images.githubusercontent.com/34682823/63210936-48265a80-c123-11e9-8974-866ccba43ccb.png)
[log.txt](https://github.com/JuPedSim/jpsreport/files/3511934/log.txt)

**Comment by gjaeger** [comment] 2019-08-17 11:19
Can you upload the file `IFD_I_corridor_tab.txt_id_1.dat`?

**Comment by gintama1227** [comment] 2019-08-17 11:27
![image](https://user-images.githubusercontent.com/34682823/63211062-ebc43a80-c124-11e9-9ea9-a923401ed895.png)
It is empty. 
I cannot upload the file now.
![image](https://user-images.githubusercontent.com/34682823/63211073-ff6fa100-c124-11e9-8a6d-5c7918d27d6d.png)

**Comment by gjaeger** [comment] 2019-08-17 11:29
Please try this file [ini_corridor_issue149.xml.zip](https://github.com/JuPedSim/jpsreport/files/3511951/ini_corridor_issue149.xml.zip).

**Comment by gintama1227** [comment] 2019-08-17 11:36
Still same problem. 

[log.txt](https://github.com/JuPedSim/jpsreport/files/3511956/log.txt)

**Comment by gjaeger** [comment] 2019-08-17 11:40
Please deactivate method A and send me the correct log-file.

**Comment by gintama1227** [comment] 2019-08-17 11:42
[log.txt](https://github.com/JuPedSim/jpsreport/files/3511961/log.txt)
![image](https://user-images.githubusercontent.com/34682823/63211228-1a431500-c127-11e9-82c2-384becd39152.png)

**Comment by gjaeger** [comment] 2019-08-17 11:44
Please change measurement area ID 1:

```
    <area_B id="1" type="BoundingBox" zPos="None">
    </area_B>
```

**Comment by gintama1227** [comment] 2019-08-17 11:49
![image](https://user-images.githubusercontent.com/34682823/63211305-f6340380-c127-11e9-9ffe-59777d0c86c1.png)
[log.txt](https://github.com/JuPedSim/jpsreport/files/3511967/log.txt)
I change the ID to 5.
![image](https://user-images.githubusercontent.com/34682823/63211316-18c61c80-c128-11e9-8499-d0b2c25f5e9d.png)
![image](https://user-images.githubusercontent.com/34682823/63211318-1e236700-c128-11e9-9f87-fe0f7556659e.png)

**Comment by gjaeger** [comment] 2019-08-17 11:51
Please try:
```
<?xml version="1.0" encoding="UTF-8"?>
<JPSreport project="JPS-Project" version="0.8" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/jps_report.xsd">

    <geometry file = "geo_corridor.xml" />

    <trajectories format="txt" unit="m">
        <file name="corridor_tab.txt" />
        <path location="./" />
    </trajectories>

    <output location="Output_issue149/" />

    <scripts location="../../scripts/"/>

    <measurement_areas unit="m">
    <area_B id="1" type="BoundingBox" zPos="None">
    </area_B>
        <area_L id="2" type="Line" zPos="None">
            <start x="0.00" y="0.00" />
            <end x="0.00" y="1.50" />
        </area_L>
    </measurement_areas>

    <velocity frame_step="10" set_movement_direction="None" ignore_backward_movement="false"/>

    <method_A enabled="false">
        <measurement_area id="2" frame_interval="100" plot_time_series="true"/>
    </method_A>

	<method_I enabled="true">
        <measurement_area id="1" start_frame="None" stop_frame="None" get_individual_FD="true" plot_time_series="false"//>
        <cut_by_circle enabled="true" radius="1.0" edges="10"/>
		<one_dimensional enabled="false"/>
    </method_I>
</JPSreport>
```

**Comment by gintama1227** [comment] 2019-08-17 11:56
![image](https://user-images.githubusercontent.com/34682823/63211383-e668ef00-c128-11e9-908a-fbb1f97752b1.png)
But there is no log.txt and no  IFD_I_corridor_tab.txt_id_1.dat

**Comment by gjaeger** [comment] 2019-08-17 11:57
Do you read the Error message? Please change your ini-file:

`<measurement_area id="1" start_frame="None" stop_frame="None" get_individual_FD="true" plot_time_series="false"/>` 

instead 

`<measurement_area id="1" start_frame="None" stop_frame="None" get_individual_FD="true" plot_time_series="false"//>`

**Comment by gintama1227** [comment] 2019-08-17 12:02
Thank you. It succeeds.
By the way, I find that I have to **Create all folders** at first (see the figure). If not, the log.txt shows "ERROR: cannot open the file individual".
![image](https://user-images.githubusercontent.com/34682823/63211464-f59c6c80-c129-11e9-8c5a-c57cee80aac9.png)

**Comment by gjaeger** [comment] 2019-08-17 12:10
> By the way, I find that I have to **Create all folders** at first (see the figure). If not, the log.txt shows "ERROR: cannot open the file individual".

@xuqiancheng Can you reproduce this problem description under Windows?

**Comment by gjaeger** [comment] 2019-08-17 12:10
> By the way, I find that I have to **Create all folders** at first (see the figure). If not, the log.txt shows "ERROR: cannot open the file individual".

That's not normal.

**Comment by gintama1227** [comment] 2019-08-17 12:13
![image](https://user-images.githubusercontent.com/34682823/63211560-6db76200-c12b-11e9-903f-b02e6eb92f72.png)
Like this.
[log.txt](https://github.com/JuPedSim/jpsreport/files/3511984/log.txt)

**Comment by xuqiancheng** [comment] 2019-08-18 15:25
> > By the way, I find that I have to **Create all folders** at first (see the figure). If not, the log.txt shows "ERROR: cannot open the file individual".
> 
@gjaeger I know this problem, but I think it has been fixed in  #144 .
@gintama1227 Could you please try the latest commit in #144 ? It should solve the problem with **Create all folders**.

**Comment by gjaeger** [comment] 2019-08-18 16:06
> I know this problem, but I think it has been fixed in #144 .

Did you test this?

**Comment by xuqiancheng** [comment] 2019-08-18 16:47
> > I know this problem, but I think it has been fixed in #144 .
> 
> Did you test this?

Yes. After compiling jpsreport on windows. I found two problems, one is can not create output folder, another one is can not read trajectory folder. Then I fixed both of them.  Now It works well on my computer.

But I have met problem when I test method I in demos/obstacle. I got empty output file as shown in the figure.
![image](https://user-images.githubusercontent.com/32732507/63227449-07901500-c1e7-11e9-8fb6-07da43591957.png)
Then I have tested method_I in demos/bottleneck, and got result. 
![image](https://user-images.githubusercontent.com/32732507/63227486-69507f00-c1e7-11e9-8f58-e9f53942dd04.png)
![image](https://user-images.githubusercontent.com/32732507/63227530-e7148a80-c1e7-11e9-9a63-31f6cf505f6c.png)
I don't know is this a normal result, since I don't know much about method I.

**Comment by gjaeger** [comment] 2019-08-18 17:22
> But I have met problem when I test method I in demos/obstacle. I got empty output file as shown in the figure.

I don't understand your problem. For this I would need the ini-file and the log-file. This [one](https://github.com/JuPedSim/jpsreport/issues/149#issuecomment-522230424) works.

> I don't know is this a normal result, since I don't know much about method I.

The method works well. [Further information](http://www.jupedsim.org/jpsreport/2016-11-01-inifile.html#method-i) can be found in the manual.

**Comment by xuqiancheng** [comment] 2019-08-18 18:42
@gjaeger  
[inifle_logfile_result.zip](https://github.com/JuPedSim/jpsreport/files/3513386/inifle_logfile_result.zip) are the inifiles, logfiles and obtained result of **demos/obstacle (corridor)** and **demos/bottleneck (bottleneck)**.
The result of **demos/bottleneck ** looks correct, but the result of **demos/obstacle** is empty.  So I don't know if the result of **demos/obstacle** is a correct result?  I can get result with other four methods and I have attached the log file here.
[log_Method_ABCD.txt](https://github.com/JuPedSim/jpsreport/files/3513419/log_Method_ABCD.txt)

**Comment by gintama1227** [comment] 2019-08-19 09:02
@xuqiancheng Thank you. It works well. 
I can get results of demos/obstacle and demos/bottleneck.

**Comment by gjaeger** [comment] 2019-08-19 09:07
@gintama1227 You get data for Method I for _ini_corridor_, too? Which changes did you make?

**Comment by gintama1227** [comment] 2019-08-20 09:05
I just follow #144 .  For ini_corridor.xml, I use the ini.xml you gave me. @gjaeger

**Closed** 2019-09-06 02:05 UTC
Labels: feature
